import { HabitDto, HabitType } from "@/lib/types/habit";
import { PencilIcon, TrashIcon } from "lucide-react";
import { habitProgress } from "@/lib/habits/progress";
import { getHabitMeta } from "@/lib/habits/habitMeta";
import { useState } from "react";

const habitClassName = (type: HabitType) => {
  if (type === "positive") {
    return "flex flex-col gap-1 rounded-md border-l-4 border-emerald-500 bg-emerald-50 p-2";
  }
  if (type === "negative") {
    return "flex flex-col gap-1 rounded-md border-l-4 border-rose-500 bg-rose-50 p-2";
  }
  return "flex flex-col gap-1 rounded-md border-l-4 border-yellow-500 bg-yellow-50 p-2";
};

const completeHabitButtonClassName = (completed: boolean) => {
  if (completed) {
    return "text-zinc-500 text-sm font-medium px-2 py-1 rounded-md border border-zinc-200 bg-zinc-100 cursor-not-allowed opacity-70 w-24 h-8";
  }
  return "text-zinc-700 text-sm font-medium px-2 py-1 rounded-md border border-zinc-300 bg-zinc-100 hover:bg-white transition-colors duration-200 w-24 h-8";
};

export default function HabitCard({ habit }: { habit: HabitDto }) {
  const [habitDataState, setHabitDataState] = useState(habit);
  const habitRow = habitDataState.habit;
  const progress = habitProgress(habitDataState);
  
  const completeHabit = () => {
    setHabitDataState({
      ...habitDataState,
      completions: [...habitDataState.completions, {
        id: habitDataState.completions.length + 1, // TODO: id should be generated by the database
        habitId: habitDataState.habit.id,
        date: new Date(),
      }],
    });
  };  
  return (
    <div className={habitClassName(habitRow.type)}>
      <div className="flex flex-row items-center justify-between gap-2">
        <p className="min-w-0 flex-1 text-lg font-bold">{habitRow.name}</p>

        <div className="flex shrink-0 flex-row items-center gap-2">
          <div className="flex flex-row items-center gap-1">
            <button
              type="button"
              onClick={completeHabit}
              disabled={progress.completedToday}
              className={completeHabitButtonClassName(progress.completedToday)}
              aria-label="Complete"
            >
              {progress.completedToday ? "Completed" : "Complete"}
            </button>

          </div>
          <button type="button" aria-label="Delete habit">
            <TrashIcon className="h-4 w-4" />
          </button>
          <button type="button" aria-label="Edit habit">
            <PencilIcon className="h-4 w-4" />
          </button>
        </div>
      </div>

      <div className="pl-2 text-left text-sm text-gray-500">
        <p>{habitRow.description}</p>
        <span className={`${getHabitMeta(habitRow).textClass}`}>
          {getHabitMeta(habitRow).label}
        </span>
      </div>
    </div>
  );
}
