"use client";

import {
  HabitDto,
  HabitReward,
  HabitRewardKind,
  HabitType,
} from "@/lib/types/habit";
import {
  CheckIcon,
  ChevronDownIcon,
  FlameIcon,
  GiftIcon,
  PencilIcon,
  TrashIcon,
} from "lucide-react";
import { habitProgress } from "@/lib/habits/progress";
import {
  streakDotClassName,
  streakFlameClassName,
  streakTone,
} from "@/lib/habits/streakStyles";
import { useRef, useState, type PointerEvent } from "react";
import { getMetaTracking } from "@/lib/habits/metaTrackingController";
import HabitCueField from "./HabitCueField";
import { enqueueHabitRewards } from "@/app/actions/items";
import Link from "next/link";

const COMPLETE_THRESHOLD = 96;
const DRAG_ACTIVATE = 8;

function formatReward(reward: HabitReward): string {
  if (reward.kind === HabitRewardKind.POINTS) {
    const points =
      typeof reward.payload === "object" &&
      reward.payload !== null &&
      "points" in reward.payload
        ? Number((reward.payload as { points: unknown }).points)
        : NaN;
    return Number.isFinite(points) ? `${points} pts` : "";
  }
  return typeof reward.payload === "string" ? reward.payload : "";
}

const habitClassName = (type: HabitType) => {
  if (type === "positive") {
    return "flex flex-col gap-1 rounded-md border-l-4 border-emerald-500 bg-emerald-50 p-2";
  }
  if (type === "negative") {
    return "flex flex-col gap-1 rounded-md border-l-4 border-rose-500 bg-rose-50 p-2";
  }
  return "flex flex-col gap-1 rounded-md border-l-4 border-yellow-500 bg-yellow-50 p-2";
};

const completeHabitButtonClassName = (completed: boolean) => {
  if (completed) {
    return "text-zinc-500 text-sm font-medium px-2 py-1 rounded-md border border-zinc-200 bg-zinc-100 cursor-not-allowed opacity-70 w-24 h-8";
  }
  return "text-zinc-700 text-sm font-medium px-2 py-1 rounded-md border border-zinc-300 bg-zinc-100 hover:bg-white transition-colors duration-200 w-24 h-8";
};

export default function HabitCard({ habit }: { habit: HabitDto }) {
  const [habitDataState, setHabitDataState] = useState(habit);
  const [dragOffset, setDragOffset] = useState(0);
  const [isDragging, setIsDragging] = useState(false);
  const [detailsOpen, setDetailsOpen] = useState(false);
  const [rewardNotice, setRewardNotice] = useState<string | null>(null);
  const dragRef = useRef<{
    startX: number;
    offset: number;
    active: boolean;
    pointerId: number | null;
  }>({ startX: 0, offset: 0, active: false, pointerId: null });

  const habitRow = habitDataState.habit;
  const progress = habitProgress(habitDataState);
  const metaTracking = getMetaTracking(habitDataState.completions, habitRow.id);
  const week = progress.weekDaysCompletion;
  const canComplete = !progress.completedToday;
  const completeProgress = Math.min(dragOffset / COMPLETE_THRESHOLD, 1);
  const streak = metaTracking.streak;
  const tone = streakTone(streak);

  const completeHabit = () => {
    if (!canComplete) return;
    const rewards = habitDataState.rewards;
    setHabitDataState({
      ...habitDataState,
      completions: [
        ...habitDataState.completions,
        {
          id: habitDataState.completions.length + 1, // TODO: id should be generated by the database
          habit: habitDataState.habit,
          date: new Date(),
        },
      ],
    });

    if (rewards.length > 0) {
      void enqueueHabitRewards(habitRow.id, rewards)
        .then(({ enqueued }) => {
          if (enqueued.length === 0) return;
          const total = enqueued.reduce((sum, item) => sum + item.quantity, 0);
          setRewardNotice(`+${total} gold queued — open in Games`);
        })
        .catch(() => {
          setRewardNotice("Could not enqueue reward");
        });
    }
  };

  const resetDrag = () => {
    dragRef.current = { startX: 0, offset: 0, active: false, pointerId: null };
    setIsDragging(false);
    setDragOffset(0);
  };

  const onPointerDown = (e: PointerEvent<HTMLDivElement>) => {
    if (!canComplete) return;
    if ((e.target as HTMLElement).closest("button")) return;

    dragRef.current = {
      startX: e.clientX,
      offset: 0,
      active: false,
      pointerId: e.pointerId,
    };
  };

  const onPointerMove = (e: PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (drag.pointerId !== e.pointerId || !canComplete) return;

    const deltaX = e.clientX - drag.startX;

    if (!drag.active) {
      if (deltaX < DRAG_ACTIVATE) return;
      drag.active = true;
      setIsDragging(true);
      e.currentTarget.setPointerCapture(e.pointerId);
    }

    const offset = Math.max(0, deltaX);
    drag.offset = offset;
    setDragOffset(offset);
  };

  const onPointerUp = (e: PointerEvent<HTMLDivElement>) => {
    const drag = dragRef.current;
    if (drag.pointerId !== e.pointerId) return;

    if (drag.active && drag.offset >= COMPLETE_THRESHOLD) {
      completeHabit();
    }

    if (e.currentTarget.hasPointerCapture(e.pointerId)) {
      e.currentTarget.releasePointerCapture(e.pointerId);
    }
    resetDrag();
  };

  return (
    <div className="relative overflow-hidden rounded-md touch-pan-y">
      <div
        className="absolute inset-0 flex items-center gap-2 bg-emerald-500 pl-4 text-sm font-medium text-white"
        aria-hidden
      >
        <CheckIcon
          className="h-5 w-5 transition-transform duration-150"
          style={{
            opacity: completeProgress,
            transform: `scale(${0.7 + completeProgress * 0.3})`,
          }}
        />
        <span style={{ opacity: completeProgress }}>Complete</span>
      </div>

      <div
        className={`${habitClassName(habitRow.type)} relative select-none ${
          isDragging ? "cursor-grabbing" : canComplete ? "cursor-grab" : ""
        }`}
        style={{
          transform: `translateX(${dragOffset}px)`,
          transition: isDragging ? "none" : "transform 200ms ease-out",
        }}
        onPointerDown={onPointerDown}
        onPointerMove={onPointerMove}
        onPointerUp={onPointerUp}
        onPointerCancel={resetDrag}
      >
        <div className="flex flex-row items-center justify-between gap-2">
          <p className="min-w-0 flex-1 text-lg font-bold">{habitRow.name}</p>

          <div className="flex shrink-0 flex-row items-center gap-2">
            <div className="flex flex-row items-center gap-1">
              <button
                type="button"
                onClick={completeHabit}
                disabled={!canComplete}
                className={completeHabitButtonClassName(!canComplete)}
                aria-label="Complete"
              >
                {canComplete ? "Complete" : "Completed"}
              </button>
            </div>
            <button type="button" aria-label="Delete habit">
              <TrashIcon className="h-4 w-4" />
            </button>
            <button type="button" aria-label="Edit habit">
              <PencilIcon className="h-4 w-4" />
            </button>
          </div>
        </div>

        <div className="flex flex-col gap-2 pl-2 text-left text-sm text-gray-500">
          <p>{habitRow.description}</p>

          {rewardNotice && (
            <p className="text-xs font-medium text-amber-700">
              {rewardNotice}{" "}
              <Link href="/games" className="underline underline-offset-2">
                Open Games
              </Link>
            </p>
          )}

          {(habitDataState.stackedAfter ||
            habitDataState.stackedInto.length > 0) && (
            <p
              className="text-xs font-medium text-zinc-600"
              aria-label="Habit stack"
            >
              {habitDataState.stackedAfter && (
                <span>
                  After{" "}
                  <span className="font-semibold text-zinc-800">
                    {habitDataState.stackedAfter.predecessor.name}
                  </span>
                </span>
              )}
              {habitDataState.stackedAfter &&
                habitDataState.stackedInto.length > 0 && (
                  <span className="text-zinc-400"> · </span>
                )}
              {habitDataState.stackedInto.length > 0 && (
                <span>
                  Then{" "}
                  <span className="font-semibold text-zinc-800">
                    {habitDataState.stackedInto
                      .map((s) => s.successor.name)
                      .join(", ")}
                  </span>
                </span>
              )}
            </p>
          )}

          <div
            className="flex items-center gap-3"
            aria-label={`Current streak: ${streak} days`}
          >
            <div className="flex items-center gap-1 tabular-nums">
              <FlameIcon
                className={`h-4 w-4 ${streakFlameClassName(tone)}`}
                fill={streak > 0 ? "currentColor" : "none"}
                aria-hidden
              />
              <span
                className={`text-sm font-semibold ${
                  streak > 0 ? "text-zinc-700" : "text-zinc-400"
                }`}
              >
                {streak}
              </span>
            </div>
            <div className="flex items-center gap-1" aria-hidden>
              {week.map((day, i) => (
                <span
                  key={i}
                  className={`rounded-[2px] ${
                    day.isToday ? "h-2 w-2" : "h-1.5 w-1.5"
                  } ${streakDotClassName(tone, day.done)}`}
                />
              ))}
            </div>
            <div className="flex items-center gap-1 ml-auto" aria-hidden>
              <GiftIcon className="h-4 w-4 text-zinc-400" />
              <p>
                {habitDataState.rewards
                  .map(formatReward)
                  .filter(Boolean)
                  .join(", ")}
              </p>
            </div>
          </div>

          <button
            type="button"
            onClick={() => setDetailsOpen((open) => !open)}
            className="flex w-full items-center gap-2 text-zinc-400 hover:text-zinc-600"
            aria-expanded={detailsOpen}
            aria-label={detailsOpen ? "Hide details" : "Show details"}
          >
            <hr className="min-w-0 flex-1 border-zinc-200" />
            <ChevronDownIcon
              className={`h-3.5 w-3.5 shrink-0 transition-transform duration-200 ${
                detailsOpen ? "rotate-180" : ""
              }`}
            />
          </button>
          {detailsOpen && (
            <div className="grid grid-cols-3 gap-x-4 gap-y-0.5 text-xs text-zinc-500">
              
              <div className="flex flex-col gap-0.5 text-xs text-zinc-600">
                {habitDataState.cues.map((cue) => (
                  <HabitCueField key={cue.id} label={cue.kind} cue={cue} />
                ))}
              </div>

              <div className="flex flex-col gap-0.5">
                <p>Created: {habitRow.createdAt.toLocaleDateString()}</p>
                <p>
                  Last completed:{" "}
                  {habitDataState.completions.length > 0
                    ? habitDataState.completions[
                        habitDataState.completions.length - 1
                      ]?.date.toLocaleDateString()
                    : "Never"}
                </p>
              </div>

              <div className="flex flex-col gap-0.5">
                <p>Streak: {metaTracking.streak}</p>
                <p>
                  Longest streak: {metaTracking.longestStreak} /{" "}
                  {metaTracking.longestCompletionStreak}
                </p>
                <p>Average streak: {metaTracking.averageStreak}</p>
                <p>
                  Average completion rate: {metaTracking.averageCompletionRate}
                </p>
              </div>

            </div>
          )}
        </div>
      </div>
    </div>
  );
}
